openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:3000
  description: Generated server url
paths:
  /todos/{id}:
    get:
      tags:
      - todo-controller
      operationId: getTodoById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Todo"
    put:
      tags:
      - todo-controller
      operationId: updateTodo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTodoRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Todo"
    delete:
      tags:
      - todo-controller
      operationId: deleteTodo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /todos:
    get:
      tags:
      - todo-controller
      operationId: getAllTodos
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      tags:
      - todo-controller
      operationId: createTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTodoRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Todo"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UpdateTodoRequest:
      required:
      - completed
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        tags:
          maxItems: 5
          minItems: 0
          type: array
          items:
            type: string
    Todo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
    CreateTodoRequest:
      required:
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        tags:
          maxItems: 5
          minItems: 0
          type: array
          items:
            type: string

security:
  - BearerAuth: []